### ISSUE TITLE
doesn't install titanium

### ISSUE THREAD

**Issue by jcowhigjr** [inakiabt/boxen-titanium#1]
Error: Parameter provider failed on Package[titanium]: Invalid package provider 'npm'
does this work for you?

**Comment by inakiabt** [comment]
Definitely, it was an issue.
I've pushed a new tag (1.2.3).  Give it a try and let me know. Thanks.

**Comment by inakiabt** [comment]
Forget about it.  It keeps not working.
The issue here is because I'm trying to install titanium via "npm" and seems, at least in this case, it requires be executed with sudo and I can't figure out how to do that.

A workaround is to execute it like "sudo boxen".

**Comment by jcowhigjr** [comment]
thanks for trying.  i may try to get it later but have a lot to read up on
to even make sense of it.

On Tuesday, April 23, 2013, inakiabt notifications@github.com wrote:

> Forget about it. It keeps not working.
> The issue here is because I'm trying to install titanium via "npm" and
> seems, at least in this case, it requires be executed with sudo and I can't
> figure out how to do that.
> 
> A workaround is to execute it like "sudo boxen".
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Sent from Gmail Mobile
